source 'https://rubygems.org'

gem 'cssbundling-rails', '~> 1.4'
gem 'dfe-wizard', path: '../../'
gem 'govuk-components'
gem 'govuk_design_system_formbuilder'
gem 'jsbundling-rails', '~> 1.3'
gem 'pg', '~> 1.6', '>= 1.6.2'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails'
gem 'sqlite3'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capybara'
  gem 'factory_bot'
  gem 'faker'
  gem 'foreman'
  gem 'pry'
  gem 'railties'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.0'
  gem 'rspec-rails'
  gem 'rubocop', '~> 1.21'
end
