source 'https://rubygems.org'

gem 'cssbundling-rails', '~> 1.4'
gem 'dfe-wizard', path: '../../'
gem 'govuk-components'
gem 'govuk_design_system_formbuilder'
gem 'jsbundling-rails', '~> 1.3'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.2.1'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'foreman'
  gem 'pry'
  gem 'rspec-rails'
end
