source 'https://rubygems.org'

gem 'puma', '>= 5.0'
gem 'rails', '~> 7.2.1'
gem 'tzinfo-data', platforms: %i[windows jruby]

gem 'dfe-wizard', path: '../../'

group :development, :test do
  gem 'pry'
end
